### PR TITLE
#57-rename-lua-class-files

### LINKED ISSUE #57: Fix source links in generated API documentation
Source links to classes are broken.

To fix this we need to rename files containing classes to CamelCase. This also includes tests.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #57

### CODE REVIEW

File: spec/unit/Environment_spec.lua [hunk 1]
```diff
@@ -19,7 +19,7 @@ local function reset_websocket_stub(stub)
             publicKeyExponent = "010001"
         }
     end
-    stub.send_login_credentials = function() return {sessionId = "sessionId0"} end
+    stub.send_login_credentials = function() return {sessionId = 12345} end
```
Comment (kaklakariada) [inline spec/unit/Environment_spec.lua:22]: string.format fails when formatting a string with `%d` in the log message. Actual value from the database is a number

File: src/Connection.lua [hunk 2]
```diff
@@ -46,8 +46,8 @@ end
 --   or nil in case there was an error executing the statement
 -- @treturn table|nil in case there was an error executing the statement or nil if the statement
 --   was executed successfully
--- [impl -> dsn~luasql-connection-execute~0]
 function Connection:execute(statement)
+    -- [impl -> dsn~luasql-connection-execute~0]
```
Comment (kaklakariada) [inline src/Connection.lua:50]: Moving the coverage tag inside the function hides it from the generated API documentation.

File: tools/runtests.sh [hunk 3]
```diff
@@ -26,5 +26,5 @@ mkdir -p "$reports_dir"
 mkdir -p "$luacov_dir"
 
 cd "$base_dir"
-luarocks test --  "$@"
+luarocks test --local -- "$@"
```
Comment (kaklakariada) [inline tools/runtests.sh:29]: Without `--local` luarocks will install to the global directory where we don't have write permissions.
